travis:
  secure:
    BINSTAR_TOKEN: YxVw9nQXZXEw2oOaODzVRvFhBpxu2LvrstLwgCvvzZTovk40NwmY9kb4A8K2SrUSliusj3bAbAbw18/7P7xFH+N1p26KsmPZSgs20Q6OXi5kfPorljTAhKdnX+MemBottZqg+fIQID0Itfg/7dEmqdrv7ROaz0NNypgPyVhdH2gHc8mU7utsKu6VY9q/+82NP5cD3qbXPdqBEr5t88KqWNsdS0lw5tQlGDtZd8Amu6Epi3oY2otVpzwCmrgXrOfkg8iF/7CphwKQCee77+hogBoWEk7BCzSuUhsZvtpzDF9s43lDhBByZpGk2vZP0Jgkk7WzKE8SmhArcDTEje4zrnbKerKVSMPQ72pCzerrABXWDh6hqoGLrnIODRw8RKiZ3h6UEKe5jSuToNpTMh5rf3whK6uE7WCwwUoYkwNxAO6YFV53nqcsuALUS0juM7zC3d+IbdEmMQgUEi2JW1y/C9ohtMEr0QNzoQyPQKYJjnlR2vUpjvHimYn98N2m55Fbu4DTRBjkmTkcjd96FyuL/PUMejKvIpUkpGn4wk2KtH7TmPte3alvDA6YB3ISy8IoTeX+T8Xh73vXVdJ2diSqbcbX8YhtNTLA9L4L8evmexErYHCl65Von2/zbBpnyB4D+IHTkLN4RTM3uXFuQCq/NlsPPy5PoRKR8V6YB9r1USk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
